### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Akhilesh6567** [Akhilesh6567/Recipe-App#3]
**As a User, I want to**  reset the password if forgotten (or) If I feel like I need to update it.

**Comment by felipehhbrito** [comment]
There needs to be a verification step to make sure this is the user who's trying to reset the password, not someone else.

**Comment by felipehhbrito** [comment]
this can be done by emailing a link to the password reset

**Comment by felipehhbrito** [comment]
How to test:
- create a dummy account
- go to the reset password screen (either via 'settings' on the dashboard or via 'forgot my password' on the login screen)
- test sending the email with a link to a screen that's not accessible through normal navigation of the app
- make sure the new password is being updated in whichever database solution we deploy
