### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Akhilesh6567** [Akhilesh6567/Recipe-App#6]
**As a user, I want to**  view my personal information like user name, User Contact details, and User Profile picture.

**Comment by AngelEldhose** [comment]
It displays all the personal information of the user like: 
- User Name
- User E-mail
- User Country
- User-preferred Language.[optional]
- User Profile Picture [optional]

**Comment by AngelEldhose** [comment]
I changed the label as delayed because I haven't done an issue which is **selecting the country**.
I changed the milestone from sprint-01 to sprint-02.
I tried to change the status to be in In-Progress but I couldn't fix it.

**Comment by AngelEldhose** [comment]
Partial of the work of this issue was done in : https://github.com/Akhilesh6567/Recipe-App/issues/24

**Comment by Akhilesh6567** [comment]
I think only the owner can change the status manually, I have pushed it to In-progress status.
