### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by felipehhbrito** [Akhilesh6567/Recipe-App#9]
**As a user, I want to**  view the reviews for the recipe.

**Comment by felipehhbrito** [comment]
There should be some kind of text message informing the sign in attempt failed for some reason.

**Comment by Akhilesh6567** [comment]
API generates the reviews which are provided by the users earlier on and they are displayed on the banner image of the Recipe.

**Comment by Akhilesh6567** [comment]
Look for the furthur update and work on it . Not that mandatory field by the end if we feel it's not helpful lets close this issue.
